### ISSUE TITLE
issue w/ side bar

### ISSUE THREAD

**Issue by gtaylor90** [t3patterson/margo-css#9]
can scroll on main page and side bar at the same time
also cuts off the bottom of the sidebar on my screen 
![screen shot 2016-08-04 at 12 06 32 pm](https://cloud.githubusercontent.com/assets/17018179/17411020/f4a7d4f2-5a3b-11e6-8560-ff9367a5d8d5.png)

**Comment by tphdev** [comment]
@gtaylor90 , thanks for pointing this out. the sidebar nav-topics at the bottom were getting covered up by a horizontal scroll bar and also the download bar in chrome

gave the `aside.sidebar` padding-bottom of 2.5rem  and it looks like that handled it.
